/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/serving/pkg/apis/autoscaling/v1alpha1"
)

// FakeActivationEndpoints implements ActivationEndpointInterface
type FakeActivationEndpoints struct {
	Fake *FakeAutoscalingV1alpha1
	ns   string
}

var activationendpointsResource = schema.GroupVersionResource{Group: "autoscaling.internal.knative.dev", Version: "v1alpha1", Resource: "activationendpoints"}

var activationendpointsKind = schema.GroupVersionKind{Group: "autoscaling.internal.knative.dev", Version: "v1alpha1", Kind: "ActivationEndpoint"}

// Get takes name of the activationEndpoint, and returns the corresponding activationEndpoint object, and an error if there is any.
func (c *FakeActivationEndpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ActivationEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(activationendpointsResource, c.ns, name), &v1alpha1.ActivationEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActivationEndpoint), err
}

// List takes label and field selectors, and returns the list of ActivationEndpoints that match those selectors.
func (c *FakeActivationEndpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ActivationEndpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(activationendpointsResource, activationendpointsKind, c.ns, opts), &v1alpha1.ActivationEndpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ActivationEndpointList{ListMeta: obj.(*v1alpha1.ActivationEndpointList).ListMeta}
	for _, item := range obj.(*v1alpha1.ActivationEndpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested activationEndpoints.
func (c *FakeActivationEndpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(activationendpointsResource, c.ns, opts))

}

// Create takes the representation of a activationEndpoint and creates it.  Returns the server's representation of the activationEndpoint, and an error, if there is any.
func (c *FakeActivationEndpoints) Create(ctx context.Context, activationEndpoint *v1alpha1.ActivationEndpoint, opts v1.CreateOptions) (result *v1alpha1.ActivationEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(activationendpointsResource, c.ns, activationEndpoint), &v1alpha1.ActivationEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActivationEndpoint), err
}

// Update takes the representation of a activationEndpoint and updates it. Returns the server's representation of the activationEndpoint, and an error, if there is any.
func (c *FakeActivationEndpoints) Update(ctx context.Context, activationEndpoint *v1alpha1.ActivationEndpoint, opts v1.UpdateOptions) (result *v1alpha1.ActivationEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(activationendpointsResource, c.ns, activationEndpoint), &v1alpha1.ActivationEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActivationEndpoint), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeActivationEndpoints) UpdateStatus(ctx context.Context, activationEndpoint *v1alpha1.ActivationEndpoint, opts v1.UpdateOptions) (*v1alpha1.ActivationEndpoint, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(activationendpointsResource, "status", c.ns, activationEndpoint), &v1alpha1.ActivationEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActivationEndpoint), err
}

// Delete takes name of the activationEndpoint and deletes it. Returns an error if one occurs.
func (c *FakeActivationEndpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(activationendpointsResource, c.ns, name), &v1alpha1.ActivationEndpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeActivationEndpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(activationendpointsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ActivationEndpointList{})
	return err
}

// Patch applies the patch and returns the patched activationEndpoint.
func (c *FakeActivationEndpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ActivationEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(activationendpointsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ActivationEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActivationEndpoint), err
}
